paniSite/formularios/urls.py
from django.conf.urls import url

from . import views


app_name = 'formularios'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^(?P<id_grafico>[0-9]+)/$', views.grafico, name='grafico'),
]

paniSite/paniSite/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from . import views

urlpatterns = [
    url(r'^formularios/', include('formularios.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^$', views.index, name='index'),
]

paniSite/formularios/models.py
from django.db import models

# Create your models here.
class Indicador(models.Model):
  indicador_text = models.CharField(max_length=200)
  fecha_publicacion = models.DateTimeField('date published')
  
  def __str__(self):
    return self.indicador_text
  
  
class Opciones(models.Model):
  indicador = models.ForeignKey(Indicador, on_delete=models.CASCADE)
  eleccion = models.CharField(max_length=200)
  cantidad = models.IntegerField(default=0)
  
  def __str__(self):
    return self.eleccion

paniSite/formularios/views.py
from django.shortcuts import render
from django.http import HttpResponse
from .models import Indicador
# Create your views here.

def index(request):
	listaIndicadores = Indicador.objects.all()
	context = {'listaIndicadores': listaIndicadores,}
	return render(request,'formularios/index.html', context)
	#return HttpResponse("Bienvenido a los formularios")

def grafico(request, id_grafico):
	context = {'id_grafico': id_grafico,}
	return render(request,'formularios/graficos.html', context)

paniSite/paniSite/views.py
from django.http import HttpResponse
# Create your views here.

def index(request):
	return HttpResponse("Bienvenido al index")

paniSite/formularios/templates/formularios/graficos.html
<script src="https://code.jquery.com/jquery-3.1.1.min.js"></script>
<script src="https://code.highcharts.com/highcharts.js"></script>
<script src="https://code.highcharts.com/modules/data.js"></script>
<script src="https://code.highcharts.com/modules/exporting.js"></script>

<!-- Additional files for the Highslide popup effect -->
<script src="https://www.highcharts.com/media/com_demo/js/highslide-full.min.js"></script>
<script src="https://www.highcharts.com/media/com_demo/js/highslide.config.js" charset="utf-8"></script>
<link rel="stylesheet" type="text/css" href="https://www.highcharts.com/media/com_demo/css/highslide.css" />

<div id="container" style="min-width: 310px; height: 400px; margin: 0 auto"></div>
<script> 
$.getJSON('https://www.highcharts.com/samples/data/jsonp.php?filename=analytics.csv&callback=?', function (csv) {

    Highcharts.chart('container', {

        data: {
            csv: csv
        },
      
        credits: {
            enabled: false
        },

        title: {
            text: 'Pani'
        },

        subtitle: {
            text: 'Source: Cochi'
        },

        xAxis: {
            tickInterval: 7 * 24 * 3600 * 1000, // one week
            tickWidth: 0,
            gridLineWidth: 1,
            labels: {
                align: 'left',
                x: 3,
                y: -3
            }
        },

        yAxis: [{ // left y axis
            title: {
                text: null
            },
            labels: {
                align: 'left',
                x: 3,
                y: 16,
                format: '{value:.,0f}'
            },
            showFirstLabel: false
        }, { // right y axis
            linkedTo: 0,
            gridLineWidth: 0,
            opposite: true,
            title: {
                text: null
            },
            labels: {
                align: 'right',
                x: -3,
                y: 16,
                format: '{value:.,0f}'
            },
            showFirstLabel: false
        }],

        legend: {
            align: 'left',
            verticalAlign: 'top',
            y: 20,
            floating: true,
            borderWidth: 0
        },

        tooltip: {
            shared: true,
            crosshairs: true
        },

        plotOptions: {
            series: {
                cursor: 'pointer',
                point: {
                    events: {
                        click: function (e) {
                            hs.htmlExpand(null, {
                                pageOrigin: {
                                    x: e.pageX || e.clientX,
                                    y: e.pageY || e.clientY
                                },
                                headingText: this.series.name,
                                maincontentText: Highcharts.dateFormat('%A, %b %e, %Y', this.x) + ':<br/> ' +
                                    this.y + ' counts',
                                width: 200
                            });
                        }
                    }
                },
                marker: {
                    lineWidth: 1
                }
            }
        },

        series: [{
            name: 'All',
            lineWidth: 4,
            marker: {
                radius: 4
            }
        }, {
            name: 'New site'
        }]
    });
});
</script>

<div> Id Grafico: {{id_grafico}}
{% for i in "xxxxxxxxxxxxxxxxxxxx" %}
  {{ forloop.counter0 }}
{% endfor %}
</div>

paniSite/formularios/templates/formularios/index.html
{% if listaIndicadores %}
    <ul>
    {% for indicador in listaIndicadores %}
        <li><a href="/formularios/{{ indicador.id }}/">{{ indicador.indicador_text }}</a></li>
        <li><a href="{% url 'formularios:grafico' indicador.id %}">{{ indicador.indicador_text }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No hay indicadores.</p>
{% endif %}